#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

### CUSTOM CONFIG #######################################################################################################

# VMware Bidirectional Copy Paste (Only for Virtual Machines)
#vmware-user-suid-wrapper &

# Wallpaper
feh --bg-scale /home/swany/Pictures/Wallpapers/GreenSkull.jpg &

# Polybar
~/.config/polybar/./launch.sh &

# Picom 
picom --config /home/swany/.config/picom/bspwm-picom.conf &

# Screen Resolution
xrandr --output eDP-1 --mode 1600x900

# RClone
rclone mount porygon:/ /home/Swany/Drive/Porygon --vfs-cache-mode writes &
rclone mount spyro:/ /home/Swany/Drive/Spyro --vfs-cache-mode writes &

# Cursor
export XCURSOR_THEME="Breeze"
export XCURSOR_SIZE=24
xsetroot -cursor_name left_ptr
